name: google_solution2
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  flutter_date_picker_timeline: ^0.3.3
  flutter_screenutil: ^5.7.0
  font_awesome_flutter: ^10.5.0
  get_it: ^7.3.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  meta: ^1.8.0
  persian_datetime_picker: ^2.6.0
  shared_preferences: ^2.1.0
  sqflite: ^2.2.8
  syncfusion_flutter_charts: ^21.1.41
  webview_flutter: ^4.2.0
  flutter_svg: 2.0.7
  another_flushbar: ^1.12.30
  # firebase_core: any
  # firebase_auth: ^4.6.3
  modal_progress_hud_nsn: ^0.4.0
  test_api: ^0.6.1
  cloud_firestore: ^4.8.2
  flutter_otp_text_field: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_native_splash:
  # the image of screen  (the image shouldn't be .svg)
  image: assets/images/logo_2000.jpg
  # background color
  color: "#ffffff"
  android: true
  ios: true